### ISSUE TITLE
Unable to delete credential

### ISSUE THREAD

**Issue by kogeletey** [r4gus/keypass#5]
When I tried to login in to the microsoft website that sent me, I got an error related to the inability to delete an entry.
What to do in this case?

**Comment by r4gus** [comment]
could you provide me with a screenshot or something so I can better understand the problem?

**Comment by kogeletey** [comment]
That's what's going on
[2024-01-29 13-29-37.webm](https://github.com/r4gus/keypass/assets/39346864/8e496044-63ae-4155-a4e0-be19f31e3585)

**Comment by r4gus** [comment]
Thanks for the video. This is probably a problem with the data store itself. I'll look into it and fix it as soon as possible. Sorry for the inconvenience.

**Comment by r4gus** [comment]
So I ran another test and it seems like I didn't fix the bug

**Comment by r4gus** [comment]
@kogeletey this sould be fixed now. You can update by running

```
sudo sh -c "$(curl -fsSL https://raw.githubusercontent.com/r4gus/keypass/master/script/install.sh)"
```

Let me know if this lets you delete the credential.

**Comment by kogeletey** [comment]
Just checked. Everything works great.
Thank you for  quickly fixing the bug.
