### ISSUE TITLE
Installation problems (install-0.3.0-beta.sh)

### ISSUE THREAD

**Issue by Saiv46** [r4gus/keypass#7]
1. Lack of verbosity

No messages on installation error, it just quietly exists.

```
saiv46@X75VC:~$ sudo ./install-0.3.0-beta.sh 
______              _   __           ______
| ___ \            | | / /          |___  /
| |_/ /_ _ ___ ___ | |/ /  ___  ___    / /
|  __/ _` / __/ __||    \ / _ \/ _ \  / /
| | | (_| \__ \__ \| |\  \  __/  __/./ /___
\_|  \__,_|___/___/\_| \_/\___|\___|\_____/

PassKeeZ Installer
------------------
Architecture:    x86_64
Package manager: apt-get
Checking dependencies... OK
Downloading Zig...
############################################################################################################################################################################################### 100,0%
Installing PassKeeZ... saiv46@X75VC:~$
```

2. Lack of caching

I'm not going to redownload dependencies, zig (especially if I already have one) and this repository with my 2mbit/s internet every time after installation failed.

![No cache?](https://github.com/r4gus/keypass/assets/47699394/c18a8337-432a-4b22-b5a2-4d64c0e54aa3)

**Comment by r4gus** [comment]
Thanks for the feedback. I've made the script more verbose, and it also reuses the downloads.
