### ISSUE TITLE
Stable Installation fails

### ISSUE THREAD

**Issue by frie** [r4gus/keypass#8]
Seems that the url for stb_image in build.zig.zon is broken:
`Fetch Packages [8/8] dvui.stb_image... /root/.cache/zig/p/1220e30b896597e843a23df3c15e9b126ed4a3d0fb042bfb7c85f7c10827bd6e66a7/build.zig.zon:14:20: error: Expected response status '200 OK' got '404 Not Found'
            .url = "https://github.com/david-vanderson/stb_image/archive/9a961327f5e67ec799bc9a6258d7abebb59d7028.tar.gz",
`

Beta install.sh currently runs **without problems**, and the passkeys **work** on Github and Microsoft (!) - not Google

**Comment by r4gus** [comment]
Thanks for the hint, I'll look into it.

**Comment by r4gus** [comment]
@frie thanks again for letting me know. When you say "not Google" do you get the same/ a similar error as shown below?

"Your device doesn't support creating passkeys. However, you can create a passkey on another device."

If so, it's an Issue with Google itself I'm unable to fix. Google seems to fingerprint the Browser and OS. I'm actually not surprised. The same time they "introduced" Passkey (its more a rebranding of FIDO2 with credential synchronization support) they (Google, Apple, Microsoft) rolled out their proprietary CTAP2 replacements. To me this is an indication that there is... let's say a lack of commitment to work on a shared standard.

Nevertheless, if you have additional information to share, I would appreciate it if you post it below.

Also, the transitive dependency issue (`stb_image`) will probably take some time to fix (I'm currently working on a new version and I'm the only maintainer with limited time).

![Screenshot from 2024-08-31 13-03-02](https://github.com/user-attachments/assets/2bc843cc-0481-4f0a-8b40-1ce16b475667)

**Comment by frie** [comment]
Yes, same error message. But that's only on Chromium. On Firefox Google also told me that my device does not support passkeys, but I could create a passkey anyway, and later also use it for authentication on Chromium.
For Github and Microsoft PasskeeZ worked on both browsers. I also tried with some php code (Wordpress plugin, Joomla module) and all this worked out of the box.
Maybe off-topic considering my initial issue, but I am missing a GUI for passkey management. Is this not longer part of the Beta binary (running as systemd service), or did I miss anything? For my physical FIDO stick I also can manage passkeys using the Chromium security settings. For PasskeeZ no such function seems to work.

**Comment by r4gus** [comment]
Thanks for the additional information. I've to do some digging regarding Google. Maybe there is a way into tricking Google with the "right" HID descriptor.

The dependency issue is quite unfortunate.

The problem is that the stable and the new version use different file formats (https://r4gus.github.io/ccdb/ + KDBX4 [currently working on it]). I'll add a command line application for managing credentials to the beta.

**Comment by frie** [comment]
I probably can await PasskeeZ making use of a kdbx4 DB - then I could use KeePassXC to manage keys in the database. Have to think further about the options arising from using kdbx4 format... Maybe integrate the PasskeeZ as a satellite DB? From the UX perspective I find PasskeeZ better than KeePassXC, because of browser independence and no need for browser addons. And using KeePassXC to manage passwords and passkeys would make much sense.

**Comment by r4gus** [comment]
I'll hit you up as soon as KDBX4 support lands.

**Comment by r4gus** [comment]
@frie I've added a command line tool for managing credentials https://github.com/r4gus/ccdb

**Comment by frie** [comment]
> @frie I've added a command line tool for managing credentials https://github.com/r4gus/ccdb

Thanks - I finally got this working without being a zig developer... Maybe an integration of the ccdb build in the passkeez beta build script (as for zigenity) would make sense. When cloning the 0.1.0 branch the build does not create binary - using the master is ok.

**Comment by r4gus** [comment]
Good point, I'll add pre-build binaries the next time.

**Comment by r4gus** [comment]
The KeePassXC discussion will be continued in #6
